# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Spectral Kurtosis
site_author: Alex Cingoranelli
site_description: RFI Reduction Package using the Spectral Kurtosis method.
repo_url: https://github.com/minifold/pytosis

edit_uri: edit/main/docs/

theme:
  name: material
  font:
    code: Fira Code
  features:
    - content.action.edit
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
  language: en

nav:
  - Home: index.md
  - API: api.md
  - Tutorials: tutorials.md
  - References: reference.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src] # search packages in src directory
          selection:
            docstring_style: "numpy"

markdown_extensions:
  - footnotes
  - abbr
  - admonition
  - def_list
