# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Spectral Kurtosis
site_author: Alex Cingoranelli
site_description: RFI Reduction Package using the Spectral Kurtosis method.
repo_url: https://github.com/minifold/pytosis

edit_uri: edit/main/docs/

theme:
  name: material
  font:
    code: Fira Code
  custom_dir: docs/material/.overrides
  features:
    - content.action.edit
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
  language: en

nav:
  - index.md
  - tutorials.md
  - reference.md

plugins:
  - mkdocstrings

markdown_extensions:
  - footnotes
  - abbr
  - admonition
  - def_list
